/**
  ******************************************************************************
  * @file    network_ecblobs.h
  * @brief   NN Code autogenerated DO NOT MODIFY IT
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2024 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */


#ifdef __cplusplus
extern "C" {
#endif

#include "ll_aton_caches_interface.h"

#include <string.h>

#if !defined(ECBLOB_CONST_SECTION)
#define ECBLOB_CONST_SECTION /* Empty */
#endif
#if !defined(ECBLOB_RUNTIME_SECTION)
#define ECBLOB_RUNTIME_SECTION /* Empty */
#endif

ECBLOB_CONST_SECTION
// aligned to the cache line size (equal to 64 bytes)
__attribute__((aligned(64)))
static const uint64_t _ec_blob_network_1[8] =
{
  0x00000002ca057a7aUL, 0x0000000c0000003dUL
};

#define _ec_blob_network_1_address _ec_blob_network_1

ECBLOB_CONST_SECTION
// aligned to the cache line size (equal to 64 bytes)
__attribute__((aligned(64)))
static const uint64_t _ec_blob_network_3[8] =
{
  0x00000002ca057a7aUL, 0x0000000c0000007dUL
};

#define _ec_blob_network_3_address _ec_blob_network_3

ECBLOB_CONST_SECTION
// aligned to the cache line size (equal to 64 bytes)
__attribute__((aligned(64)))
static const uint64_t _ec_blob_network_6[8] =
{
  0x00000002ca057a7aUL, 0x0000000c000000ddUL
};

#define _ec_blob_network_6_address _ec_blob_network_6

ECBLOB_CONST_SECTION
// aligned to the cache line size (equal to 64 bytes)
__attribute__((aligned(64)))
static const uint64_t _ec_blob_network_8[8] =
{
  0x00000002ca057a7aUL, 0x0000000c0000011dUL
};

#define _ec_blob_network_8_address _ec_blob_network_8

ECBLOB_CONST_SECTION
// aligned to the cache line size (equal to 64 bytes)
__attribute__((aligned(64)))
static const uint64_t _ec_blob_network_11[8] =
{
  0x00000002ca057a7aUL, 0x0000000c0000017dUL
};

#define _ec_blob_network_11_address _ec_blob_network_11

ECBLOB_CONST_SECTION
// aligned to the cache line size (equal to 64 bytes)
__attribute__((aligned(64)))
static const uint64_t _ec_blob_network_13[8] =
{
  0x00000002ca057a7aUL, 0x0000000c000001bdUL
};

#define _ec_blob_network_13_address _ec_blob_network_13

// this macro returns true if _ec_blob_network_1 blob is encrypted and must be decrypted on the fly, false otherwise
#define LL_ATON_EC_MustDecryptBlob_network__ec_blob_network_1 false

// this macro returns true if _ec_blob_network_3 blob is encrypted and must be decrypted on the fly, false otherwise
#define LL_ATON_EC_MustDecryptBlob_network__ec_blob_network_3 false

// this macro returns true if _ec_blob_network_6 blob is encrypted and must be decrypted on the fly, false otherwise
#define LL_ATON_EC_MustDecryptBlob_network__ec_blob_network_6 false

// this macro returns true if _ec_blob_network_8 blob is encrypted and must be decrypted on the fly, false otherwise
#define LL_ATON_EC_MustDecryptBlob_network__ec_blob_network_8 false

// this macro returns true if _ec_blob_network_11 blob is encrypted and must be decrypted on the fly, false otherwise
#define LL_ATON_EC_MustDecryptBlob_network__ec_blob_network_11 false

// this macro returns true if _ec_blob_network_13 blob is encrypted and must be decrypted on the fly, false otherwise
#define LL_ATON_EC_MustDecryptBlob_network__ec_blob_network_13 false

// this function MUST be called ONLY ONCE once for initializing the network
bool LL_ATON_EC_Network_Init_network(void)
{
  return true;
}

// this function should be called before each inference
bool LL_ATON_EC_Inference_Init_network(void)
{
  return true;
}

#ifdef __cplusplus
}
#endif
